name: Heroku Deployment

on: []

jobs:
  # If tests succeeded and we are on main then the repository will be deploy
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HD_PROD_DATABASE_NAME: 'prodDB'
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HD_JWT_EXPIRES: '1h'
          HD_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          HD_SENDGRID_SENDER: 'patricklachlanbell@gmail.com'
          HD_REDIRECT_RULS: '/docs'
